### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by jason-personalis** [genome/tigra-sv#2]
I am getting a segmentation fault from tigra-sv (using the latest code).  Here is a gdb backtrace:
```
(gdb) run -w 1000 -c 5 -R $REFPATH/hs37d5.fa -q 20 -N 7 -r  -I $OUTPATH -k 51,61 NA12878.svcnv.gff.chromosome_5.intermed.pcr $BAMPATH/NA12878.chromosome_5.recal.bam
Starting program
#16 SVs to be assembled from
#Bams: $BAMPATH/NA12878.chromosome_5.recal.bam
#Version-       Parameters: 
#CHR1   POS1    CHR2    POS2    ORI     SIZE    TYPE    HET     wASMSCORE       TRIMMED_CONTIG_SIZE     ALIGNED%        NUM_SEG NUM_FSUB        NUM_FINDEL      BP_FINDEL       MicroHomology   MicroInsertion  PREFIX  ASMPARM CopyNumber      Gene    Known
5.486805.5.487700.DEL.896.+-    a: 50   b: 100
Use samtools faidx to fetch fai
Reference: 0x67d3d0
$BAMPATH/NA12878.chromosome_5.recal.bam
$BAMPATH/NA12878.chromosome_5.recal.bam5:486305-486855

Program received signal SIGSEGV, Segmentation fault.
0x000000000043694c in get_chunk_coordinates (idx=0x6bc790, tid=4, beg=486304, end=486855, cnt_off=0x7fffffffc350) at /home/jharris/Code/tigra-sv/src/exe/tigra-sv/samtools.h:105
105             index = idx->index[tid];
Missing separate debuginfos, use: debuginfo-install glibc-2.12-1.132.el6.x86_64 libgcc-4.4.7-11.el6.x86_64 libstdc++-4.4.7-11.el6.x86_64 zlib-1.2.3-29.el6.x86_64
(gdb) bt
#0  0x000000000043694c in get_chunk_coordinates (idx=0x6bc790, tid=4, beg=486304, end=486855, cnt_off=0x7fffffffc350) at /home/jharris/Code/tigra-sv/src/exe/tigra-sv/samtools.h:105
#1  0x000000000046496d in assemble::ReadBamChr_prep (this=0x7fffffffda40, chr_str="5:486305-486855", bam_name="/hpc/research/data/test/pipeline/atlas_core_runs/wgs/150630_173352/pipeline_output/NA12878.chromosome_5.recal.bam", tid=0x7fffffffc35c, beg=0x7fffffffc358, 
    end=0x7fffffffc354, in=0x6bdbf0, n_off=0x7fffffffc350) at /home/jharris/Code/tigra-sv/src/exe/tigra-sv/main.cpp:4745
#2  0x000000000046b368 in assemble::AssembleBestSV (this=0x7fffffffda40, prefix="5.486805.5.487700.DEL.896.+-", SV=..., a=50, b=100) at /home/jharris/Code/tigra-sv/src/exe/tigra-sv/main.cpp:5223
#3  0x000000000046eb7e in assemble::assemble_func (this=0x7fffffffda40) at /home/jharris/Code/tigra-sv/src/exe/tigra-sv/main.cpp:5522
#4  0x000000000043794c in main (argc=18, argv=0x7fffffffdd38) at /home/jharris/Code/tigra-sv/src/exe/tigra-sv/main.cpp:5665
```
(EDIT: I realized I didn't compile with debug symbols enabled, so I recompiled and fixed the backtrace lines above)

I am reluctant to also attach the BAM file; let me know if you need it.  Here is the content of the input SV file (NA12878.svcnv.gff.chromosome_5.intermed.pcr):
```
5       486805  486805  487700  487700  DEL     896     BWA     ILL             HS      Personalis
5       1663730 1663730 1664300 1664300 DEL     571     BWA     ILL             HS      Personalis
5       3638077 3638077 3639400 3639400 DEL     1324    BWA     ILL             HS      Personalis
5       12426001        12426001        12426700        12426700        DEL     700     BWA     ILL             HS      Personalis
5       15942661        15942661        15943200        15943200        DEL     540     BWA     ILL             HS      Personalis
5       21450201        21450201        21452500        21452500        DEL     2300    BWA     ILL             HS      Personalis
5       23903001        23903001        23905212        23905212        DEL     2212    BWA     ILL             HS      Personalis
5       54401806        54401806        54402144        54402144        DEL     339     BWA     ILL             HS      Personalis
5       88606301        88606301        88607080        88607080        DEL     780     BWA     ILL             HS      Personalis
5       136854701       136854701       136856400       136856400       DEL     1700    BWA     ILL             HS      Personalis
5       137807500       137807500       137816900       137816900       DEL     9401    BWA     ILL             HS      Personalis
5       147462156       147462156       147462546       147462546       DEL     391     BWA     ILL             HS      Personalis
5       167401101       167401101       167401400       167401400       DEL     300     BWA     ILL             HS      Personalis
5       170129811       170129811       170131461       170131461       DEL     1651    BWA     ILL             HS      Personalis
5       177821919       177821919       177823794       177823794       DEL     1876    BWA     ILL             HS      Personalis
5       178109098       178109098       178113473       178113473       DEL     4376    BWA     ILL             HS      Personalis
```

**Comment by ernfrid** [comment]
I apologize for the inconvenience, but we're no longer maintaining TIGRA. Ken Chen's lab at MD Anderson has newer versions and support contact information available here: http://bioinformatics.mdanderson.org/main/TIGRA.

I've updated the repo to indicate this so others know where to go as well. Best of luck.
